# Generated by Django 4.1.7 on 2024-01-13 06:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('app', '0012_profile_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
